### PR TITLE
feat: add github workflow template files

### PR DESCRIPTION
**Pull request by helsner**

### CODE REVIEW

**Review by twojtylak — CHANGES_REQUESTED** [review]
Not necessary there are already workflow files.... https://github.com/DFAU/ext-skeleton/tree/main/.github

**Comment by helsner** [comment]
> Not necessary there are already workflow files.... https://github.com/DFAU/ext-skeleton/tree/main/.github

Ah, are they in the right place then? They're not within the `skel` directory and were not created in my case

**Comment by twojtylak** [comment]
Yes, in the skeleton directory there are only the files with placeholders that will be replaced.

**After running:**
`composer create-project toujou/ext-skeleton test_henni --repository="{\"url\": \"https://github.com/DFAU/ext-skeleton.git\", \"type\": \"vcs\"}" --stability=dev --remove-vcs`

I see:
```
➜  test_henni ls -alth
total 88
drwxr-xr-x   19 tobiaswojtylak  staff   608B Feb 27 14:26 .
-rw-r--r--    1 tobiaswojtylak  staff   1.4K Feb 27 14:26 composer.json
-rw-r--r--    1 tobiaswojtylak  staff    56B Feb 27 14:26 ext_localconf.php
-rw-r--r--    1 tobiaswojtylak  staff    20B Feb 27 14:26 ext_tables.sql
-rw-r--r--    1 tobiaswojtylak  staff   424B Feb 27 14:26 ext_emconf.php
-rw-r--r--    1 tobiaswojtylak  staff   153B Feb 27 14:26 .gitignore
-rw-r--r--    1 tobiaswojtylak  staff    58B Feb 27 14:26 typoscript-lint.yml
-rw-r--r--    1 tobiaswojtylak  staff   704B Feb 27 14:26 README.md
-rw-r--r--    1 tobiaswojtylak  staff   728B Feb 27 14:26 .editorconfig
drwxr-xr-x    4 tobiaswojtylak  staff   128B Feb 27 14:26 etc
drwxr-xr-x    4 tobiaswojtylak  staff   128B Feb 27 14:26 Tests
-rw-r--r--    1 tobiaswojtylak  staff    62B Feb 27 14:26 phpstan.neon
drwxr-xr-x    3 tobiaswojtylak  staff    96B Feb 27 14:26 Classes
-rw-r--r--    1 tobiaswojtylak  staff    56B Feb 27 14:26 ext_tables.php
drwxr-xr-x    5 tobiaswojtylak  staff   160B Feb 27 14:26 Configuration
-rw-r--r--    1 tobiaswojtylak  staff   598B Feb 27 14:26 composer.lock
drwxr-xr-x    4 tobiaswojtylak  staff   128B Feb 27 14:26 vendor
drwxr-xr-x@ 227 tobiaswojtylak  staff   7.1K Feb 27 14:26 ..
drwxr-xr-x    4 tobiaswojtylak  staff   128B Feb 22 15:33 .github
➜  test_henni 

```

**Comment by helsner** [comment]
ah, seems like they got lost on my end when moving stuff around

**Pull request closed without merging**
